# Copyright 2020 QuantumBlack Visual Analytics Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
# NONINFRINGEMENT. IN NO EVENT WILL THE LICENSOR OR OTHER CONTRIBUTORS
# BE LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF, OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# The QuantumBlack Visual Analytics Limited ("QuantumBlack") name and logo
# (either separately or in combination, "QuantumBlack Trademarks") are
# trademarks of QuantumBlack. The License does not grant you any right or
# license to the QuantumBlack Trademarks. You may not use the QuantumBlack
# Trademarks or any confusingly similar mark as a trademark for your product,
# or use the QuantumBlack Trademarks in any other manner that might cause
# confusion in the marketplace, including but not limited to in advertising,
# on websites, or on software.
#
# See the License for the specific language governing permissions and
# limitations under the License.

"""
This is a boilerplate pipeline 'pdf_scrap'
generated using Kedro 0.16.2
"""

from kedro.pipeline import Pipeline, node
from .nodes import (
    tidy_data,
    buscar_violencia_genero,
    buscar_violencia_fisica,
    buscar_info_denunciante,
    buscar_genero_den,
    buscar_nacionalidad_denunciante,
    buscar_est_civil_denunciente,
    buscar_edad_denunciante,
    buscar_est_denunciante,
    buscar_domic_denunciante,
    buscar_villa_denunciante,
    buscar_ocupac_denunciante,
    buscar_info_acusado,
    buscar_genero_acusado,
    buscar_nacionalidad_acusado,
    buscar_est_civil_acusado,
    buscar_edad_acusado,
    buscar_instruccion_acusado,
    buscar_domicilio_acusado,
    buscar_ocupacion_acusado,
    buscar_relacion,
    chequear_conv,
    buscar_vinculos,
    buscar_info_episodio,
    buscar_denuncia_anterior,
    buscar_medidas_prot,
    buscar_dia_hecho,
    buscar_conclusiones,
    buscar_riesgo,
    buscar_numero_legajo,
    buscar_informe_final,
    buscar_violencia_psico,
    buscar_violencia_econ,
    buscar_violencia_sex,
    buscar_violencia_soc,
    buscar_violencia_amb,
    buscar_violencia_simb,
    buscar_hijos,
    buscar_hijos_en_comun,
    buscar_frecuencia,
    buscar_dijo,
    buscar_dijo_sin_comillas,
    buscar_comillas,
    buscar_fecha_del_hecho,
    buscar_fecha_denuncia,
    buscar_horario_hecho,
    to_excel,
)


def create_pipeline(**kwargs):
    return Pipeline(
        [
            node(
                func=tidy_data,
                inputs="filt_list",
                outputs="data",
            ),
            node(
                func=buscar_numero_legajo,
                inputs="data",
                outputs="numero_legajo",
            ),
            node(
                func=buscar_violencia_genero,
                inputs="data",
                outputs="violencia_de_genero",
            ),
            node(
                func=buscar_violencia_fisica,
                inputs="data",
                outputs="violencia_fisica",
            ),
            node(
                func=buscar_info_denunciante,
                inputs="data",
                outputs="info_denunciante",
            ),
            node(
                func=buscar_info_acusado,
                inputs="data",
                outputs="info_acusado",
            ),
            node(
                func=buscar_genero_den,
                inputs="info_denunciante",
                outputs="genero_denunciante",
            ),
            node(
                func=buscar_nacionalidad_denunciante,
                inputs="info_denunciante",
                outputs="nacionalidad_denunciante",
            ),
            node(
                func=buscar_est_civil_denunciente,
                inputs="info_denunciante",
                outputs="est_civil_denunciante",
            ),
            node(
                func=buscar_edad_denunciante,
                inputs="info_denunciante",
                outputs="edad_denunciante",
            ),
            node(
                func=buscar_est_denunciante,
                inputs="info_denunciante",
                outputs="est_denunciante",
            ),
            node(
                func=buscar_domic_denunciante,
                inputs="info_denunciante",
                outputs="domic_denunciante",
            ),
            node(
                func=buscar_villa_denunciante,
                inputs="info_denunciante",
                outputs="villa_denunciante",
            ),
            node(
                func=buscar_ocupac_denunciante,
                inputs="info_denunciante",
                outputs="ocupac_denunciante",
            ),
            node(
                func=buscar_genero_acusado,
                inputs="info_acusado",
                outputs="genero_acusado",
            ),
            node(
                func=buscar_nacionalidad_acusado,
                inputs="info_acusado",
                outputs="nacionalida_acusado",
            ),
            node(
                func=buscar_est_civil_acusado,
                inputs="info_acusado",
                outputs="est_civil_acusado",
            ),
            node(
                func=buscar_edad_acusado,
                inputs="info_acusado",
                outputs="edad_acusado",
            ),
            node(
                func=buscar_instruccion_acusado,
                inputs="info_acusado",
                outputs="instruccion_acusado",
            ),
            node(
                func=buscar_domicilio_acusado,
                inputs="info_acusado",
                outputs="domicilio_acusado",
            ),
            node(
                func=buscar_ocupacion_acusado,
                inputs="info_acusado",
                outputs="ocupacion_acusado",
            ),
            node(
                func=buscar_relacion,
                inputs="info_acusado",
                outputs="relacion",
            ),
            node(
                func=chequear_conv,
                inputs="info_acusado",
                outputs="convivencia",
            ),
            node(
                func=buscar_info_episodio,
                inputs="data",
                outputs="info_episodio",
            ),
            node(
                func=buscar_denuncia_anterior,
                inputs="info_episodio",
                outputs="denuncia_anterior",
            ),
            node(
                func=buscar_medidas_prot,
                inputs="info_episodio",
                outputs="medidas_prot",
            ),
            node(
                func=buscar_dia_hecho,
                inputs="data",
                outputs="dia_hecho",
            ),
            node(
                func=buscar_conclusiones,
                inputs="data",
                outputs="conclusiones",
            ),
            node(
                func=buscar_riesgo,
                inputs="conclusiones",
                outputs="riesgo",
            ),
            node(
                func=buscar_informe_final,
                inputs="data",
                outputs="informe_final",
            ),
            node(
                func=buscar_violencia_amb,
                inputs="informe_final",
                outputs="violencia_amb",
            ),
            node(
                func=buscar_violencia_econ,
                inputs="informe_final",
                outputs="violencia_econ",
            ),
            node(
                func=buscar_violencia_genero,
                inputs="informe_final",
                outputs="violencia_genero",
            ),
            node(
                func=buscar_violencia_psico,
                inputs="informe_final",
                outputs="violencia_psico",
            ),
            node(
                func=buscar_violencia_sex,
                inputs="informe_final",
                outputs="violencia_sex",
            ),
            node(
                func=buscar_violencia_simb,
                inputs="informe_final",
                outputs="violencia_simb",
            ),
            node(
                func=buscar_violencia_soc,
                inputs="informe_final",
                outputs="violencia_soc",
            ),
            node(
                func=buscar_hijos,
                inputs="informe_final",
                outputs="hijos",
            ),
            node(
                func=buscar_hijos_en_comun,
                inputs="hijos",
                outputs="hijos_en_comun",
            ),
            node(
                func=buscar_frecuencia,
                inputs="informe_final",
                outputs="frecuencia",
            ),
            node(
                func=buscar_dijo,
                inputs="data",
                outputs="frases_agresion",
            ),
            node(
                func=buscar_dijo_sin_comillas,
                inputs="data",
                outputs="frases_sin_comillas",
            ),
            node(
                func=buscar_comillas,
                inputs="data",
                outputs="frases_comillas",
            ),
            node(
                func=buscar_fecha_del_hecho,
                inputs=["info_episodio", "fecha_denuncia"],
                outputs="fecha_del_hecho",
            ),
            node(
                func=buscar_horario_hecho,
                inputs="info_episodio",
                outputs="horario_hecho",
            ),
            node(
                func=buscar_fecha_denuncia,
                inputs="data",
                outputs="fecha_denuncia",
            ),
            node(
                func=to_excel,
                inputs=[
                    "violencia_de_genero",
                    "violencia_fisica",
                    "genero_denunciante",
                    "nacionalidad_denunciante",
                    "est_civil_denunciante",
                    "edad_denunciante",
                    "est_denunciante",
                    "domic_denunciante",
                    "villa_denunciante",
                    "ocupac_denunciante",
                    "genero_acusado",
                    "nacionalida_acusado",
                    "est_civil_acusado",
                    "edad_acusado",
                    "instruccion_acusado",
                    "domicilio_acusado",
                    "ocupacion_acusado",
                    "relacion",
                    "convivencia",
                    "denuncia_anterior",
                    "medidas_prot",
                    "dia_hecho",
                    "riesgo",
                    "violencia_psico",
                    "violencia_econ",
                    "violencia_sex",
                    "violencia_soc",
                    "violencia_amb",
                    "violencia_simb",
                    "hijos_en_comun",
                    "frecuencia",
                    "frases_sin_comillas",
                    "frases_agresion",
                    "frases_comillas",
                    "fecha_del_hecho",
                    "fecha_denuncia",
                    "horario_hecho",
                    "numero_legajo",
                ],
                outputs="excel_ovd_data",
            ),
        ]
    )
